<?php
namespace app\admin\controller;

use think\Controller;

class Executiveflight extends Controller{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if(!session('loginId')){
            $this->redirect('admin/user/login');
        }
    }

    //list
    public function executive(){

        $res = model('Executiveflight')->query("
            select m.execId,m.shippingId,m.salePrice,m.discount,m.remains,m.isMeal,p.shippingGrade grade from
            (select a.execId,a.execDate,a.execPrice,a.status,a.estimateDeparture,a.estimateArrival,b.shippingId,b.salePrice,b.discount,b.remains,b.isMeal,
            e.airportName depart,f.cityName departCity
            from executiveflight a,tickettypes b,flight c,terminal d,airport e,city f
            where a.execId=b.execId and a.flightId=c.flightId and c.departTerminal=d.terminalId and d.airportId=e.airportId and e.cityId=f.cityId
            )m, 
            (select a.execId,a.execDate,a.execPrice,a.status,a.estimateDeparture,a.estimateArrival,b.shippingId,b.salePrice,b.discount,b.remains,b.isMeal,
            e.airportName depart,f.cityName arrivalCity
            from executiveflight a,tickettypes b,flight c,terminal d,airport e,city f
            where a.execId=b.execId and a.flightId=c.flightId and c.arrivalTerminal=d.terminalId and d.airportId=e.airportId and e.cityId=f.cityId
            )n, shipping p
            where m.execId=n.execId and m.shippingId=p.shippingId and m.shippingId=n.shippingId;");

        $list = model('Executiveflight')->query("
            select DISTINCT m.execId,m.execDate,m.execPrice,m.status,m.estimateDeparture,m.estimateArrival,m.depart depart,m.deTerName,m.boardingGate,n.depart arrival,n.arTerName,m.departCity,n.arrivalCity from
            (select a.execId,a.execDate,a.execPrice,a.status,a.estimateDeparture,a.estimateArrival,a.boardingGate,b.shippingId,b.salePrice,b.discount,b.remains,b.isMeal,
            e.airportName depart,f.cityName departCity,d.terminalName deTerName
            from executiveflight a,tickettypes b,flight c,terminal d,airport e,city f
            where a.execId=b.execId and a.flightId=c.flightId and c.departTerminal=d.terminalId and d.airportId=e.airportId and e.cityId=f.cityId
            )m, 
            (select a.execId,a.execDate,a.execPrice,a.status,a.estimateDeparture,a.estimateArrival,b.shippingId,b.salePrice,b.discount,b.remains,b.isMeal,
            e.airportName depart,f.cityName arrivalCity,d.terminalName arTerName
            from executiveflight a,tickettypes b,flight c,terminal d,airport e,city f
            where a.execId=b.execId and a.flightId=c.flightId and c.arrivalTerminal=d.terminalId and d.airportId=e.airportId and e.cityId=f.cityId
            )n, shipping p
            where m.execId=n.execId and m.shippingId=p.shippingId and m.shippingId=n.shippingId;");

        $i=0;$j=0;
        $grade = array();
        $result = array();
        foreach ($res as $value){
            if($j!=0 && $j%3==0){
                $i++;
                $j=0;
            }
            $grade[$i][$j]= $value;
            $j++;
        }
        $i=0;
        foreach ($list as $value){
            $result[$i] = $value;
            $result[$i]['grade'] = $grade[$i];
            $i++;
        }

        $this->assign('list',$result);
        return view();
    }

    public function execsearch(){

        //传过来的值
        $data = [
            'depart' => input('depart'),
            'arrival' => input('arrival'),
            'execDate' => input('execDate'),
        ];

        $res = model('Executiveflight')->search($data);
        if($res=="未查找到航班信息！"){
            $this->error($res);
        }else{
            $this->assign('list',$res);
        }
        return $this->fetch();

    }

    //存放数据
    public function infosave(){

        if(request()->isAjax()){
            $data = [
                'depart' => input('depart'),
                'arrival' => input('arrival'),
                'departTime' => input('departTime'),
                'totalPrice' => input('totalPrice'),
                'execId' => input('execId'),
                'boardingGate' => input('boardingGate'),
            ];
            session('order',$data);
            $res = model('Executiveflight')->infosave($data);
            if($res==1){
                $this->success("加载中...",'admin/executiveflight/infosave');
            }else{
                $this->error($res);
            }
        }
        return view();
    }

}