<?php
namespace app\admin\controller;

use think\Controller;

class Flight extends Controller{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if(!session('loginId')){
            $this->redirect('admin/user/login');
        }
    }

    public function main(){
        $list = model('Flight')->query("        select m.depart,n.arrival,m.price,m.departureTime from
                                                              (select a.flightId,d.cityName depart,a.price,a.departureTime
                                                               from flight a,terminal b, airport c, city d
                                                               where a.departTerminal = b.terminalId
                                                                 and b.airportId=c.airportId
                                                                 and c.cityId=d.cityId
                                                              )m,
                                                              (select a.flightId,d.cityName arrival,a.price,a.departureTime
                                                               from flight a,terminal b, airport c, city d
                                                               where a.arrivalTerminal = b.terminalId
                                                                 and b.airportId=c.airportId
                                                                 and c.cityId=d.cityId
                                                              )n
        where m.flightId=n.flightId
        order by m.price asc
            limit 8;");
        $this->assign('list',$list);

        return $this->fetch();
    }


}