<?php
namespace app\admin\controller;

use think\Controller;

class Link extends Controller{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if(!session('loginId')){
            $this->redirect('admin/user/login');
        }
    }

    public function linkadd(){

        $data = [
            'loginId' => session('loginId'),
            'userId' => session('userId'),
            'idNumber' => session('idNumber'),
        ];
        $time_stamp = strtotime(date('Y-m-d H:i:s'));
        $date = date('Y-m-d H:i:s',$time_stamp);
        $data['linkTime'] = $date;
        $res = model('Link')->linkadd($data);
        if($res==1){
            session('url',"admin/order/orderadd");
        }
        return view();
    }

    public function linkdelete(){
        $data = [
            'idNumber' => session("idNumberDel"),
            'loginId' => session("loginId"),
        ];

        model('Link')->where([
            'idNumber' => $data['idNumber'],
            'loginId' => $data['loginId']
        ])->delete();

        return view();
    }
}
