<?php
namespace app\admin\controller;

use think\Controller;

class Seatchosen extends Controller{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if(!session('loginId')){
            $this->redirect('admin/user/login');
        }
    }

    public function seatadd(){

        if(request()->isAjax()){
            $temp = session('order');
            $data = [
                'seatId' => input("seatId"),
                'execId' => $temp['execId'],
                'ticketId' => session("ticketId"),
                'seatStatus' => input("seatStatus"),
            ];
            session("seatId",$data['seatId']);
            $res = model("Seatchosen")->seatadd($data);
            if($res==1){
                $this->success("选座成功",'admin/ticket/ticketedit');
            }else {
                $this->error($res);
            }
        }
        return view();
    }
}