<?php
namespace app\admin\controller;

use think\Controller;

class Seat extends Controller{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if(!session('loginId')){
            $this->redirect('admin/user/login');
        }
    }

    public function seatlist(){

        $data = [
            'shippingId' =>input('shippingId'),
        ];
        $res = model("Seat")->query("select * from seat where aircraftId=? and shippingId=?;",[1,$data['shippingId']]);

        $this->assign("list",$res);
        return view();
    }
}