<?php
namespace app\admin\controller;

use think\Controller;

class Ticket extends Controller{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if(!session('loginId')){
            $this->redirect('admin/user/login');
        }
    }

    public function finish(){
        return view();
    }

    //添加
    public function ticketadd(){
        if(request()->isAjax()){
            $ticketId = (string)session('loginId').(string)session('userId');
            $order = session('order');
            $data = [
                'ticketId' => $ticketId,
                'orderId' => session('orderId'),
                'idNumber' => session('idNumber'),
                'execId' => $order['execId'],
                'shippingId' => input('shippingId'),
                'seatId' => input('seatId'),
                'cost' => input('cost'),
                'insurance' => input('insurance'),
                'totalcost' => input('totalcost'),
                'remark' => input('remark'),
                'isCheckIn' => input('isCheckIn'),
                'boardingNumber' => $order['boardingGate'],
            ];
            $res = model('Ticket')->ticketadd($data);
            session("orderId",$data['orderId']);
            if($res==1){
                $this->success("加载中...",'admin/ticket/finish');
            }else{
                $this->error($res);
            }
        }
        return view();
    }

    public function ticketlist(){
        $ticketId = (string)session('loginId').(string)session('userId');
        session("ticketId",$ticketId);
        $res = model("Ticket")->query("        
        select a.*,b.shippingGrade,b.shippingId,c.passName from ticket a,shipping b,passenger c
        where a.shippingId=b.shippingId and a.idNumber=c.idNumber
            and ticketId=?;",[$ticketId]);

        $this->assign("list",$res);
        return view();
    }

    //delete
    public function ticketdelete(){

        $data = [
            'orderId' => session("orderIdDel"),
        ];

        model('Ticket')->where([
            'orderId' => $data['orderId'],
        ])->delete();
        return view();
    }

    //修改
    public function ticketedit(){

        $data = [
            'orderId' => session("orderId"),
            'seatId' => session("seatId"),
        ];
        model("Ticket")

            ->where('orderId',$data['orderId'])
            ->setField('seatId',$data['seatId']);
        return view();
    }


}